apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: pred
  labels:
    app: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: asia-southeast1-docker.pkg.dev/project-79fc9abe-eb97-46c9-b31/predictive-maintenance/notifications-service:3243604bb403f656398a7bdbc71460926bb630ac
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8083
              protocol: TCP

          env:
            # Kafka
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: KAFKA_BROKERS

            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: NOTIFICATIONS_KAFKA_TOPIC

            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: NOTIFICATIONS_KAFKA_GROUP_ID

            # Database
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notifications-db-secret
                  key: DATABASE_URL

            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: KEYCLOAK_URL

            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              value: "notifications-service"

            - name: KEYCLOAK_CLIENT_SECRET
              value: "dev-notifications-service-secret"

            - name: FAILURE_THRESHOLD
              value: "0.1"

          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #     ephemeral-storage: "512Mi"
          #   limits:
          #     cpu: "250m"
          #     memory: "256Mi"
          #     ephemeral-storage: "1Gi"
