apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: predictive-maintenance

resources:
  - ../../base

images:
  - name: predictive-maintenance-frontend
    newName: registry.digitalocean.com/predictive-maintenance/predictive-maintenance-frontend
    newTag: latest
  - name: predictive-maintenance-api-gateway
    newName: registry.digitalocean.com/predictive-maintenance/predictive-maintenance-api-gateway
    newTag: latest
  - name: predictive-maintenance-ingestion
    newName: registry.digitalocean.com/predictive-maintenance/predictive-maintenance-ingestion
    newTag: latest
  - name: predictive-maintenance-event-processing
    newName: registry.digitalocean.com/predictive-maintenance/predictive-maintenance-event-processing
    newTag: latest
  - name: predictive-maintenance-ml
    newName: registry.digitalocean.com/predictive-maintenance/predictive-maintenance-ml
    newTag: latest
  - name: predictive-maintenance-notification
    newName: registry.digitalocean.com/predictive-maintenance/predictive-maintenance-notification
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: prod
    includeSelectors: false
    includeTemplates: true
