apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: pred
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          image: asia-southeast1-docker.pkg.dev/project-79fc9abe-eb97-46c9-b31/predictive-maintenance/web-frontend:f048ac35375dfcff76046b9b981272422d25a68a
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: NODE_ENV

            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: NEXTAUTH_URL

            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: NEXTAUTH_SECRET

            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: KEYCLOAK_URL

            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: KEYCLOAK_REALM

            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: KEYCLOAK_CLIENT_ID

            - name: KEYCLOAK_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: web-frontend-config
                  key: KEYCLOAK_PUBLIC_URL

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: KEYCLOAK_CLIENT_SECRET

            - name: NEXT_PUBLIC_API_GATEWAY_URL
              value: "https://kong.nsanjula.xyz"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "512Mi"
          #     ephemeral-storage: "1Gi"
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #     ephemeral-storage: "2Gi"
