apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: pred
  labels:
    app: web-frontend
spec:
  type: ClusterIP
  selector:
    app: web-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
