apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: pred
  labels:
    app: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: asia-southeast1-docker.pkg.dev/project-79fc9abe-eb97-46c9-b31/predictive-maintenance/ai-ml:72b03e93381b78ecf63afb7d32ed45c56c5209bd
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8084
              protocol: TCP

          env:
            # HTTP server
            - name: ML_PORT
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: ML_PORT

            - name: ML_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: ML_LOG_LEVEL

            # Database
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ml-db-secret
                  key: DATABASE_URL

            # Kafka
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: KAFKA_BROKERS

            - name: ML_FEATURES_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: ML_FEATURES_TOPIC

            - name: ML_KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: ML_KAFKA_GROUP_ID

            - name: ML_KAFKA_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: ML_KAFKA_OFFSET_RESET

          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "512Mi"
          #     ephemeral-storage: "1Gi"
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #     ephemeral-storage: "2Gi"
