apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: pred
  labels:
    app: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.1
          imagePullPolicy: IfNotPresent

          args:
            - start-dev

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - configMapRef:
                name: keycloak-config

          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: KC_DB_USERNAME

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: KC_DB_PASSWORD

            - name: KC_HEALTH_ENABLED
              value: "true"

            - name: KC_METRICS_ENABLED
              value: "true"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          # resources:
          #   requests:
          #     cpu: "500m"
          #     memory: "1Gi"
          #     ephemeral-storage: "1Gi"
          #   limits:
          #     cpu: "1"
          #     memory: "2Gi"
          #     ephemeral-storage: "2Gi"
