apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: pred
  labels:
    app: ingestion-service
spec:
  type: ClusterIP
  selector:
    app: ingestion-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
