apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: pred
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    per_listener_settings false

    listener 8883 0.0.0.0
    protocol mqtt

    cafile /mosquitto/certs/ca.crt
    certfile /mosquitto/certs/server.crt
    keyfile /mosquitto/certs/server.key

    require_certificate false
    use_identity_as_username false

    allow_anonymous false
    password_file /mosquitto/data/passwordfile

    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information

  entrypoint.sh: |
    #!/bin/sh
    set -e

    echo "Creating Mosquitto password file..."

    rm -f /mosquitto/data/passwordfile

    mosquitto_passwd -b -c /mosquitto/data/passwordfile "$MQTT_DEVICE_USERNAME" "$MQTT_DEVICE_PASSWORD"
    mosquitto_passwd -b /mosquitto/data/passwordfile "$MQTT_INGESTION_USERNAME" "$MQTT_INGESTION_PASSWORD"

    chown mosquitto:mosquitto /mosquitto/data/passwordfile
    chmod 600 /mosquitto/data/passwordfile

    echo "Starting Mosquitto broker..."

    exec mosquitto -c /mosquitto/config/mosquitto.conf
