apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predictive-maintenance
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/predictive-maintenance.git
    targetRevision: main
    path: newfolder/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: predictive-maintenance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
