apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processing-service
  namespace: pred
  labels:
    app: event-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-processing-service
  template:
    metadata:
      labels:
        app: event-processing-service
    spec:
      containers:
        - name: event-processing-service
          image: asia-southeast1-docker.pkg.dev/project-79fc9abe-eb97-46c9-b31/predictive-maintenance/event-processing-service:6c3d246cd9cbb6fbcca242c0ec47edc983d9c205
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8082
              protocol: TCP

          env:
            # Kafka
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: KAFKA_BROKERS

            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: KAFKA_TOPIC

            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: EVENT_KAFKA_GROUP_ID

            # Database
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: events-db-secret
                  key: DATABASE_URL

            # HTTP server
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: EVENT_HTTP_PORT

          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #     ephemeral-storage: "512Mi"
          #   limits:
          #     cpu: "250m"
          #     memory: "256Mi"
          #     ephemeral-storage: "1Gi"
