apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processing-service
  namespace: pred
  labels:
    app: event-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-processing-service
  template:
    metadata:
      labels:
        app: event-processing-service
    spec:
      containers:
        - name: event-processing-service
          image: asia-southeast1-docker.pkg.dev/project-79fc9abe-eb97-46c9-b31/predictive-maintenance/event-processing-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "device-events"
            - name: KAFKA_GROUP_ID
              value: "event-processing-service"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/events"
            - name: HTTP_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
