apiVersion: v1
kind: Service
metadata:
  name: event-processing-service
  namespace: pred
  labels:
    app: event-processing-service
spec:
  type: ClusterIP
  selector:
    app: event-processing-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
