apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: predictive-maintenance

resources:
  - namespace.yaml
  - storageclass.yaml
  - secrets.yaml
  - kafka.yaml
  - shared-db.yaml
  - notification-db.yaml
  - ingestion.yaml
  - event-processing.yaml
  - ml.yaml
  - notification.yaml
  - api-gateway.yaml
  - frontend.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: predictive-maintenance
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
