apiVersion: v1
kind: Secret
metadata:
  name: shared-db-secret
type: Opaque
stringData:
  username: pm_user
  password: pm_password_change_me
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-db-secret
type: Opaque
stringData:
  username: notify_user
  password: notify_password_change_me
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-app-secret
type: Opaque
stringData:
  mail-api-key: replace-with-real-mail-api-key
